name: rysolve
description: Minimalistic goal tracker.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.4+6

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.2.1
  provider: ^6.0.3
  shared_preferences: ^2.5.5
  table_calendar: ^3.0.7
  awesome_dialog: ^3.0.2
  loader_overlay: ^5.0.0
  introduction_screen: ^4.0.0
  flutter_svg: ^2.3.0
  url_launcher: ^6.3.2
  package_info_plus: ^10.2.1
  sqflite: ^2.4.3
  path: ^1.8.2
  fl_chart: ^1.2.0
  just_audio: ^0.10.6
  flutter_file_dialog: ^3.3.2
  path_provider: ^2.1.6
  awesome_notifications: ^0.12.1
  timezone: ^0.11.1
  flutter_colorpicker: ^1.0.3
  flutter_launcher_icons: ^0.14.4
  firebase_core: ^4.14.0
  firebase_analytics: ^12.5.0
  firebase_messaging: ^16.0.0
  google_mobile_ads: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

# For now mipmaps are used.
flutter_icons:
  image_path_android: "assets/images/icon.png"
  image_path_ios: "assets/images/ios_icon.jpg"
  adaptive_icon_foreground: "assets/images/android_foreground.png"
  adaptive_icon_background: "#FFFFFF"
  min_sdk_android: 21
  android: true
  ios: true
  remove_alpha_ios: true

flutter:
  uses-material-design: true

    config:
    enable-swift-package-manager: false

  assets:
    - assets/
    - assets/images/
    - assets/images/onboard/
    - assets/sounds/
    - assets/google_fonts/
