// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEr9vd88Kn0wH61IdRmNI74wqAqZvOwoE',
    appId: '1:261034992845:android:61c9b571b4291661503584',
    messagingSenderId: '261034992845',
    projectId: 'rysolve-app-2026',
    storageBucket: 'rysolve-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7Xc_Fc4XEcG7wq1elsEAi9toeDxP6Ky8',
    appId: '1:261034992845:ios:91ceb36f85d9a3e8503584',
    messagingSenderId: '261034992845',
    projectId: 'rysolve-app-2026',
    storageBucket: 'rysolve-app-2026.firebasestorage.app',
    iosBundleId: 'com.nwhator.rysolve',
  );
}